### PR TITLE
Put BT back in targetBaud if failed to detect baud rate

### LINKED ISSUE #482: If a BT client is already connected,  RCP leaves baud rate at 9600
if RCP starts up and BT is already connected it leaves the default baud rate at 9600 (the last baud rate it attempted), and then the tablet never can communicate, b/c wrong baud rate.

Under this condition it should reset it to the default programmed baud rate. 

BT: Trying Baudrate: 115200
BT: Trying Baudrate: 57600                                                                                           
BT: Trying Baudrate: 9600                                                                                            
BT: Could not detect device using known baud rates.                                                                  
BT: Failed to communicate with device.                                                                               
BT: Failed to provision module. A client may already be connected.

### PR DESCRIPTION
**Pull request by stieg**
Fixes #482

### CODE REVIEW

File: src/devices/bluetooth.c [hunk 1]
```diff
@@ -230,6 +234,10 @@ int bt_init_connection(DeviceConfig *config)
         switch (baud) {
         case 0:
                 pr_info("BT: Failed to communicate with device.\r\n");
+
+                /* Restore the targetBaud rate in case alreay in command mode */
```
Comment (brentpicasso) [inline src/devices/bluetooth.c]: typo  - already

**Comment by brentpicasso** [comment]
:ship:
