### PR TITLE
switch lua virtual channels to base 1.  Resolves #1094

### LINKED ISSUE #1094: in lua, user defined channels should be 1 based
this script should detect and produce an error:

a=addChannel("a", 50 )
setChannel(b,10)

instead it happily sets channel "a" to 10.  
Since we can't change lua's init to zero behaviour, we should avoid 0 as a valid channel Id.

### PR DESCRIPTION
**Pull request by RodADavison**
I'm optimistically submitting this, hoping you'll reconsider.  It took me much less time to write this code than it did to debug one script for one user.  It's not fair to give users tools that don't give them a chance to find their own errors.

### CODE REVIEW

File: src/lua/luaLoggerBinding.c [hunk 1]
```diff
@@ -951,15 +952,18 @@ static int lua_get_virtual_channel(lua_State *ls)
                 }
         }
         /* Return nil, channel not found */
```
Comment (brentpicasso) [inline src/lua/luaLoggerBinding.c:954]: Code comment does not match code behavior.

**Review by brentpicasso — CHANGES_REQUESTED** [review]
Looks good, only one small change request.

**Comment by brentpicasso** [comment]
Looks good overall. When committing code, please run it through bin/style.h first.  I'll do that now on the 2.18.2 code.

**Comment by brentpicasso** [comment]
Ok, r/2.18.2 has been updated with bin/style.sh. 

You can merge r/2.18.2 and also apply bin/style.sh to your branch.  Thanks!

**Review by brentpicasso — APPROVED** [review]
