### PR TITLE
corrected units for OBD2 speed conversion

### LINKED ISSUE #472: KPH to MPH conversion is incorrect
Should be kph * 0.621371

### PR DESCRIPTION
**Pull request by brentpicasso**
resolves #472

### CODE REVIEW

File: src/OBD2/OBD2.c [hunk 1]
```diff
@@ -53,7 +53,7 @@ static float celcius_to_farenheight(float celcius)
 
 static float kph_to_mph(float kph)
 {
-    return kph * 1.60934;
+    return kph * 0.621371;
```
Comment (stieg) [inline src/OBD2/OBD2.c]: This is good.  I'm going to file a ticket to centralize where we do our unit conversions so we can unit test them going forward.
